### ISSUE TITLE
Do not overwrite default debug viewhelper

### ISSUE THREAD

**Issue by sascha-egerer** [NamelessCoder/typo3-cms-fluid-debug#3]
IMO the default debug viewhelper should not be overridden or the overwrite should have the same functionality like the default debug viewhelper.
The debug viewhelper of that packages is by default "inline" and does not have an "inline" property like the default one.
So it's hard for someone who is used to the default viewhelper.

**Comment by DanielRuf** [comment]
In my opinion the readme is clear enough, and you can also create an alias for the original VH probably.

> This package contains overrides and additions to the standard Fluid debugging utility in TYPO3 CMS. It replaces the normal debugging ViewHelper with an improved version that solves several known problems. In addition to dumping variables it also allows you to insert xdebug break points in Fluid templates via a ViewHelper.

**Comment by NamelessCoder** [comment]
It's easy enough to add an extension configuration option for this, it's just a matter of creating a different namespace alias in the `TYPO3_CONF_VARS` instead of extending `f`. Valid feature request, I expect to add this at some point unless someone beats me to it with a pull request ;)

**Comment by sascha-egerer** [comment]
That's exactly what i would prefer. Add the viewhelper but keep the existing unless someone really don't wan't the original
